### PR TITLE
Improving user experience

### PR DESCRIPTION
**Pull request by dayveed-repo**
- added sufficient spacing to elements in the garage and the select car modal for each plan
- fixed the overlaying button on the scan page and request maintenance page

### CODE REVIEW

**Comment by dayveed-repo** [comment]
i need the url to the launch_site/privacy-policy in other to link to the native app

**Review by Dami-Olus — APPROVED** [review]
ok approved

**Comment by dayveed-repo** [comment]
- Made the membership plan universal
- Made the membership plan show in the home page
- Made the basket and checkout flexible to different plans

**Comment by dayveed-repo** [comment]
prevented data from showing in other users homepage when users accounts are changed

**Review by Dami-Olus — APPROVED** [review]
Ok to merge after updating plan icons on home page to be rounded

**Pull request merged**
